# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('People', '0001_initial'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('assignmentTitle', models.CharField(max_length=50, verbose_name='Title')),
                ('assignmentText', models.CharField(max_length=500, verbose_name='Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments', models.ManyToManyField(to='CourseMatter.Assignment')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(verbose_name='Marks Obtained')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lectureID', models.AutoField(primary_key=True, serialize=False)),
                ('lectureTitle', models.CharField(max_length=50, verbose_name='Title')),
                ('lectureText', models.CharField(max_length=500, verbose_name='Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionText', models.CharField(max_length=100, verbose_name='Question')),
                ('choice1', models.CharField(max_length=50, verbose_name='Choice 1')),
                ('choice2', models.CharField(max_length=50, verbose_name='Choice 2')),
                ('choice3', models.CharField(max_length=50, verbose_name='Choice 3')),
                ('choice4', models.CharField(max_length=50, verbose_name='Choice 4')),
                ('questionMarks', models.IntegerField(verbose_name='Question Marks')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testID', models.AutoField(primary_key=True, serialize=False)),
                ('testTitle', models.CharField(max_length=50, verbose_name='Title')),
                ('questions', models.ManyToManyField(to='CourseMatter.Question')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='testID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseMatter.Test'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='lectures',
            field=models.ManyToManyField(to='CourseMatter.Lecture'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='tests',
            field=models.ManyToManyField(to='CourseMatter.Test'),
        ),
    ]
