# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseMatter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lectureWeek',
            field=models.IntegerField(null=True, verbose_name='Week No.'),
        ),
    ]
