# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50, verbose_name='Course Name')),
                ('courseField', models.CharField(max_length=50, verbose_name='Course Field')),
                ('prerequisites', models.CharField(max_length=200, verbose_name='Pre-requisites')),
                ('faculties', models.ManyToManyField(to='People.Faculty')),
            ],
        ),
    ]
