# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='course',
            name='endDate',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='course',
            name='startDate',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
