# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyToParentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailSubject', models.CharField(max_length=50, verbose_name='Mail Subject')),
                ('mailText', models.CharField(max_length=500, verbose_name='Mail Body')),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Faculty')),
                ('parententID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyToStudentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailSubject', models.CharField(max_length=50, verbose_name='Mail Subject')),
                ('mailText', models.CharField(max_length=500, verbose_name='Mail Body')),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Faculty')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ParentToFacultyMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailSubject', models.CharField(max_length=50, verbose_name='Mail Subject')),
                ('mailText', models.CharField(max_length=500, verbose_name='Mail Body')),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Faculty')),
                ('parentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentToFacultyMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailSubject', models.CharField(max_length=50, verbose_name='Mail Subject')),
                ('mailText', models.CharField(max_length=500, verbose_name='Mail Body')),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Faculty')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Student')),
            ],
        ),
    ]
