# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultytoparentmail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facultytostudentmail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parenttofacultymail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studenttofacultymail',
            name='id',
        ),
        migrations.AddField(
            model_name='facultytoparentmail',
            name='mailID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='facultytostudentmail',
            name='mailID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='parenttofacultymail',
            name='mailID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studenttofacultymail',
            name='mailID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
